config/routes.rb
Rails.application.routes.draw do
  get 'application_forms/index'

  get 'academic_year/index'

  get 'visiting_hours/index'

  get 'contact/index'

  get 'grades/index'

  get 'timetable_changes/index'

  get 'useful_links/index'

  get 'home/index'

  root 'home#index'
  
  devise_for :users, path_names: {
  	sign_up: ''
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


    def email_required?
    	false
  	end

  	def email_changed?
    	false
  	end
end

app/controllers/academic_year_controller.rb
class AcademicYearController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 	protect_from_forgery with: :exception
 	before_action :authenticate_user!
 	rescue_from ActionController::RoutingError, with: :not_found
 	layout :layout_by_resource

	def not_found
		respond_to do |format|
      		format.html { redirect_to root_path, notice: "Error, wrong params in the request - record could not be found" }
      		format.json { head :not_found }
      	end
	end

  	protected

  	def layout_by_resource
    	if devise_controller?
      		"devise"
    	else
      		"application"
    	end
  	end
end

app/controllers/application_forms_controller.rb
class ApplicationFormsController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/timetable_changes_controller.rb
class TimetableChangesController < ApplicationController
  def index
  end
end

app/controllers/useful_links_controller.rb
class UsefulLinksController < ApplicationController
  def index
  end
end

app/controllers/visiting_hours_controller.rb
class VisitingHoursController < ApplicationController
  def index
  end
end

app/helpers/academic_year_helper.rb
module AcademicYearHelper
end

app/helpers/application_forms_helper.rb
module ApplicationFormsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/timetable_changes_helper.rb
module TimetableChangesHelper
end

app/helpers/useful_links_helper.rb
module UsefulLinksHelper
end

app/helpers/visiting_hours_helper.rb
module VisitingHoursHelper
end

app/views/academic_year/index.html.erb
<div class="grid academic-year">
	<div class="grid-item 1/1 academic-year-title">
		Academic Year 2016/2017
	</div>

	<div class="grid-item 1/1 academic-year-list">
		<div class="grid-item 1/1 academic-year-semester">
			<div id="winter-title" class="academic-year-semester-title">
				<i class="fa fa-angle-double-right"></i> Winter Semester (26/09/2016 – 19/02/2017)
			</div>
			<div id="winter-content" class="academic-year-semester-content">
				<table>
					<colgroup>
	        			<col class="4/10">
	        			<col class="3/10">
	        			<col class="3/10">
	      			</colgroup>
	      			<thead>
	      				<tr>
	      					<th></th>
	      					<th class="centered">From</th>
	      					<th class="centered">To</th>
	      				</tr>
	      			</thead>
					<tbody>
						<tr>
							<td>Classes</td>
							<td class="centered">26/09/2016</td>
							<td class="centered">24/01/2017</td>
						</tr>
						<tr>
							<td>Christmas Break</td>
							<td class="centered">22/12/2016</td>
							<td class="centered">02/01/2017</td>
						</tr>
						<tr>
							<td>Examination Session I</td>
							<td class="centered">25/01/2017</td>
							<td class="centered">05/02/2017</td>
						</tr>
						<tr>
							<td>Winter Break</td>
							<td class="centered">06/02/2017</td>
							<td class="centered">12/02/2017</td>
						</tr>
						<tr>
							<td>Examination Session II</td>
							<td class="centered">13/02/2017</td>
							<td class="centered">19/02/2017</td>
						</tr>
						<tr>
							<td>Mid-semester break</td>
							<td class="centered">20/02/2017</td>
							<td class="centered">26/02/2017</td>
						</tr>
					</tbody>
				</table>
				Notes:
				<ul>
					<li>31/10/2016 - no classes</li>
					<li>09/11/2016 - Friday's schedule</li>
					<li>03/01/2017 - Friday's schedule</li>
				</ul>
			</div>
		</div>

		<div class="grid-item 1/1 academic-year-semester">
			<div id="spring-title" class="academic-year-semester-title">
				<i class="fa fa-angle-double-right"></i> Spring Semester (27/02/2017 - 27/09/2017)
			</div>
			<div id="spring-content" class="academic-year-semester-content">
				<table>
					<colgroup>
	        			<col class="4/10">
	        			<col class="3/10">
	        			<col class="3/10">
	      			</colgroup>
	      			<thead>
	      				<tr>
	      					<th></th>
	      					<th class="centered">From</th>
	      					<th class="centered">To</th>
	      				</tr>
	      			</thead>
					<tbody>
						<tr>
							<td>Classes</td>
							<td class="centered">27/02/2017</td>
							<td class="centered">21/06/2017</td>
						</tr>
						<tr>
							<td>Spring Break</td>
							<td class="centered">14/04/2017</td>
							<td class="centered">18/04/2017</td>
						</tr>
						<tr>
							<td>Examination Session I</td>
							<td class="centered">22/06/2017</td>
							<td class="centered">05/07/2017</td>
						</tr>
						<tr>
							<td>Summer Break</td>
							<td class="centered">06/07/2017</td>
							<td class="centered">03/09/2017</td>
						</tr>
						<tr>
							<td>Examination Session II</td>
							<td class="centered">04/09/2017</td>
							<td class="centered">14/09/2017</td>
						</tr>
						<tr>
							<td>Mid-semester break</td>
							<td class="centered">15/09/2017</td>
							<td class="centered">27/09/2017</td>
						</tr>
					</tbody>
				</table>
				Notes:
				<ul>
					<li>14/06/2017 - Friday's schedule</li>
				</ul>
			</div>
		</div>
	</div>
</div>

app/views/application_forms/index.html.erb
<div class="grid application-forms">
	<div class="grid-item 1/1 application-forms-title">
		Application forms
	</div>

	<div class="grid-item 1/1 application-forms-list">
		<div class="grid-item 1/1 application-forms-item">
			<div class="application-forms-item-title">
				<%= link_to asset_path("deans_leave.pdf"), title: "Dean's leave application form" do %> 
					<i class="fa fa-angle-double-right"></i> Dean's leave
				<% end %>
			</div>
			<div class="application-forms-item-description">
				Application to the Dean of the Faculty for a leave of absence.
			</div>
		</div>

		<div class="grid-item 1/1 application-forms-item">
			<div class="application-forms-item-title">
				<%= link_to asset_path("extracurricular.pdf"), title: "Extracurricular subjects application form" do %> 
					<i class="fa fa-angle-double-right"></i> Extracurricular subjects
				<% end %>
			</div>
			<div class="application-forms-item-description">
				Application to the Dean of the Faculty for permission to study extracurricular subjects.
			</div>
		</div>

		<div class="grid-item 1/1 application-forms-item">
			<div class="application-forms-item-title">
				<%= link_to asset_path("resignation.pdf"), title: "Studies resignation form" do %> 
					<i class="fa fa-angle-double-right"></i> Studies resignation
				<% end %>
			</div>
			<div class="application-forms-item-description">
				The request for removal from the list of students.
			</div>
		</div>

		<div class="grid-item 1/1 application-forms-item">
			<div class="application-forms-item-title">
				<%= link_to asset_path("repeat_semester.pdf"), title: "Repeat semester application form" do %> 
					<i class="fa fa-angle-double-right"></i> Repeat semester
				<% end %>
			</div>
			<div class="application-forms-item-description">
				Application to the Dean of the Faculty for permission to resume studies by submitting an examination.
			</div>
		</div>

		<div class="grid-item 1/1 application-forms-item">
			<div class="application-forms-item-title">
				<%= link_to asset_path("resit_exam.pdf"), title: "Request exam resit" do %> 
					<i class="fa fa-angle-double-right"></i> Exam resit
				<% end %>
			</div>
			<div class="application-forms-item-description">
				Application to the Dean of the Faculty for permission to take a board resit examination.
			</div>
		</div>
	</div>
</div>

app/views/contact/index.html.erb
<div class="grid contact-list">
	<div class="grid-item 1/1 contact-title">
		Contacts
	</div>

	<div class="grid-item 1/1 contact-item">
		<div class="grid-item 1/1 contact-name">
			<i class="fa fa-angle-double-right"></i> Lodz University of Technology
		</div>
		<div class="grid-item 1/1">
			<table>
				<colgroup>
        			<col class="1/10">
        			<col class="9/10">
      			</colgroup>
				<tbody>
					<tr class="contact-address">
						<td>Address:</td>
						<td>ul. Żeromskiego 116<br>90-924 Łódź</td>
					</tr>
					<tr class="contact-phone">
						<td>Phone:</td>
						<td class="phone-number">(48) (42) 636 55 22</td>
					</tr>
					<tr class="contact-phone">
						<td>Fax:</td>
						<td class="phone-number">(48) (42) 636 56 15</td>
					</tr>
					<tr class="contact-mail">
						<td>E-Mail:</td>
						<td class="mail">sekretariat@p.lodz.pl</td>
					</tr>
					<tr class="contact-webpage">
						<td>Webpage:</td>
						<td><a href="http://www.p.lodz.pl">www.p.lodz.pl</a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<div class="grid-item 1/1 contact-item">
		<div class="grid-item 1/1 contact-name">
			<i class="fa fa-angle-double-right"></i> International Faculty of Egineering
		</div>
		<div class="grid-item 1/1">
			<table>
				<colgroup>
        			<col class="1/10">
        			<col class="9/10">
      			</colgroup>
				<tbody>
					<tr class="contact-address">
						<td>Address:</td>
						<td>ul. Żwirki 36<br>90-924 Łódź</td>
					</tr>
					<tr class="contact-phone">
						<td>Phone:</td>
						<td class="phone-number">(48) 42-638-38-00</td>
					</tr>
					<tr class="contact-phone">
						<td>Fax:</td>
						<td class="phone-number">(48) 42-631-32-49</td>
					</tr>
					<tr class="contact-mail">
						<td>E-Mail:</td>
						<td class="mail">ife@adm.p.lodz.pl</td>
					</tr>
					<tr class="contact-webpage">
						<td>Webpage:</td>
						<td><a href="http://www.ife.p.lodz.pl">www.ife.p.lodz.pl</a></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/grades/index.html.erb
<div class="grid grades">
	<div class="grid-item 1/1 select-sem">
		<div id="sem-dropdown" class="grid-item 1/1 select-sem-dropdown">
			Select semester <i class="fa fa-angle-down"></i>
		</div>

		<div id="sem-list" class="grid-item 1/1 select-sem-list">
			<div id="sem1" class="grid-item 1/1 select-sem-list-item">
				<i class="fa fa-angle-right"></i> Semester 1 - Winter 2014
			</div>
			<div id="sem2" class="grid-item 1/1 select-sem-list-item">
				<i class="fa fa-angle-right"></i> Semester 2 - Spring 2015
			</div>
			<div id="sem3" class="grid-item 1/1 select-sem-list-item">
				<i class="fa fa-angle-right"></i> Semester 3 - Winter 2015
			</div>
			<div id="sem4" class="grid-item 1/1 select-sem-list-item">
				<i class="fa fa-angle-right"></i> Semester 4 - Spring 2016
			</div>
			<div id="sem5" class="grid-item 1/1 select-sem-list-item">
				<i class="fa fa-angle-right"></i> Semester 5 - Winter 2016
			</div>
		</div>
	</div>

	<div id="sem-selected-container" class="grid-item 1/1 select-sem hidden">
		<div id="sem-selected" class="grid-item 1/1 select-sem-selected">
		</div>
	</div>

	<div id="grades-here" class="grid-item 1/1 compact-1/1 grades-table">
		<div id="id-sem1" class="sem-hidden">
			<%= render 'shared/grades/grades_sem1' %>
		</div>
		<div id="id-sem2" class="sem-hidden">
			<%= render 'shared/grades/grades_sem2' %>
		</div>
		<div id="id-sem3" class="sem-hidden">
			<%= render 'shared/grades/grades_sem3' %>
		</div>
		<div id="id-sem4" class="sem-hidden">
			<%= render 'shared/grades/grades_sem4' %>
		</div>
		<div id="id-sem5" class="sem-hidden">
			<%= render 'shared/grades/grades_sem5' %>
		</div>
	</div>
</div>

app/views/home/index.html.erb
<%= render 'shared/announcements' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TUL | Web dean's office</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div class="grid below-navbar">

      <div class="grid-item 1/5 medium-hidden compact-hidden">
        <div class="grid-item 1/1">
          <%= render 'shared/timetable_changes_last' %>
        </div>
        <div class="grid-item 1/1">
          <%= render 'shared/useful_links' %>
        </div>
      </div>

      <div class="grid-item 4/5 medium-1/1 compact-1/1">
        <%= yield %>
      </div>

    </div>
    
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TUL | Web dean's office</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <div class="container">

    <div class="grid hidden compact-visible logo-mobile">
      <div class="grid-item 1/1 text-center logo-tul mobile">
        Lodz University of Technology
        <hr>
      </div>
      <div class="grid-item 1/1 logo">
        <span class="logo-web">
          Web
        </span>

        <span class="logo-office">
          dean's office
        </span>
      </div>  
    </div>

    <div class="grid compact-hidden logo-regular">
      <div class="grid-item 1/1 text-center logo-tul">
        <%= image_tag("logo_PL.jpg", size: "50x78", alt: "") %> Lodz University of Technology
        <hr>
      </div>
    </div>

    <div class="grid compact-hidden logo-regular">
      <div class="grid-item 1/1 logo">
        <font class="logo-web">
          Web
        </font>

        <font class="logo-office">
          dean's office
        </font>
      </div>
    </div>

    <%= yield %>

  </div>
  
  </body>
</html>

app/views/shared/_alerts.html.erb
<div id="message-holder" class="grid grid-center">
  <% if notice %>
    <div class="grid-item 3/4 compact-1/1 box message-box message-normal">
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert %>
    <div class="grid-item 3/4 compact-1/1 box message-box message-critical">
      <p><%= alert %></p>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="app-footer">
  <div class="grid">
    
    <div class="grid-item 1/1 text-center">
      Made with <%= image_tag("ruby.png", size: "20x20", alt: "Ruby") %> on Rails
    </div>

    <div class="grid-item 1/1 text-center">
      Tomasz Prochniewicz &copy <%= DateTime.now.year %>
    </div>

  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-navbar">

	<div class="grid">

		<div class="grid-item 1/3 medium-4/5 compact-4/5 navbar-left">
			<ul>
				<li>
					<%= link_to root_path do %>  
        				<span class="logo-web logo-nav">
         					Web
        				</span>

       					<span class="logo-office logo-nav">
       						dean's office
       					</span>
					<% end %>
				</li>
			</ul>
		</div>

		<label for="navbar-checkbox" class="grid-item medium-1/5 compact-1/5 hidden medium-visible compact-visible navbar-right">
          <i class="fa fa-bars"></i>
        </label>
      	<input type="checkbox" id="navbar-checkbox" class="hidden">

		<div class="grid-item 1/3 medium-hidden compact-hidden navbar-center">
			<ul>
				<li>
					<%= link_to root_path, title: "Home" do %> 
						<i class="fa fa-home"></i>
					<% end %>
				</li>
				<li>
					<a href="https://cas.p.lodz.pl/cas/login?service=https://virtul.p.lodz.pl/spe">
						<i class="fa fa-envelope"></i>
					</a>
				</li>
				<li>
					<%= link_to grades_index_path, title: "Grades" do %> 
						<i class="fa fa-book"></i>
					<% end %>
				</li>
				<li>
					<%= link_to asset_path("5CS1.pdf"), title: "Your timetable" do %> 
						<i class="fa fa-calendar"></i>
					<% end %>
				</li>
			</ul>
		</div>

		<div class="grid-item 1/3 medium-hidden compact-hidden navbar-right">
			<ul>
				<li class="user-name">
					<%= current_user.first_name %> <%= current_user.last_name %>
				</li>
				<li>
					<%= link_to edit_user_registration_path, title: "Edit profile" do %>
						<i class="fa fa-cog"></i>
					<% end %>
				</li>
				<li>
					<%= link_to destroy_user_session_path, title: "Sign out", method: :delete do %> 
						<i class="fa fa-sign-out"></i>
					<% end %>
				</li>
			</ul>
		</div>

	</div>

</div>

<div id="toggle-mobile-menu" class="navbar fixed-mobile-menu mobile-menu navbar-center">
	<ul>
		<li>
			<%= link_to root_path, title: "Home" do %> 
				<i class="fa fa-home"></i>
			<% end %>
		</li>
		<li>
			<a href="https://cas.p.lodz.pl/cas/login?service=https://virtul.p.lodz.pl/spe" title="E-Mail client">
				<i class="fa fa-envelope"></i>
			</a>
		</li>
		<li>
			<%= link_to grades_index_path, title: "Grades" do %> 
				<i class="fa fa-book"></i>
			<% end %>
		</li>
		<li>
			<%= link_to asset_path("5CS1.pdf"), title: "Your timetable" do %> 
				<i class="fa fa-calendar"></i>
			<% end %>
		</li>
		<li>
			<%= link_to timetable_changes_index_path, title: "Timetable changes" do %> 
				<i class="fa fa-calendar-times-o"></i>
			<% end %>
		</li>
		<li>
			<%= link_to useful_links_index_path, title: "Useful links" do %> 
				<i class="fa fa-external-link"></i>
			<% end %>
		</li>
		<li class="compact-hidden">
			<%= link_to edit_user_registration_path, title: "Edit profile" do %>
				<i class="fa fa-cog"></i>
			<% end %>
		</li>
		<li>
			<%= link_to destroy_user_session_path, title: "Sign out", method: :delete do %> 
				<i class="fa fa-sign-out"></i>
			<% end %>
		</li>
	</ul>
</div>

app/views/shared/_timetable_changes_last.html.erb
<div class="grid timetable-changes-last">

	<div id="time-tab-drop" class="grid-item 1/1 timetable-changes-last-dropdown">
		New timetable changes <i class="fa fa-angle-down"></i>
	</div>

	<div id="time-tab-list" class="grid-item 1/1 timetable-changes-last-list">
		<div class="grid-item 1/1 timetable-changes-last-list-item">
			<div class="grid-item 1/1 timetable-changes-last-list-item-subject">
				<i class="fa fa-angle-right"></i> GUI programming
			</div>
			<div class="grid-item 1/1 timetable-changes-last-list-item-message">
				On 18/11 classes will start at 12:30 pm.
			</div>
		</div>
		<div class="grid-item 1/1 timetable-changes-last-list-item">
			<div class="grid-item 1/1 timetable-changes-last-list-item-subject">
				<i class="fa fa-angle-right"></i> Embedded systems
			</div>
			<div class="grid-item 1/1 timetable-changes-last-list-item-message">
				Classes on 21/11 are cancelled.
			</div>
		</div>
	</div>

</div>

app/views/shared/_useful_links.html.erb
<div class="grid useful-links">

	<div id="use-ful-drop" class="grid-item 1/1 useful-links-dropdown">
		Useful links <i class="fa fa-angle-down"></i>
	</div>

	<div id="use-ful-links" class="grid-item 1/1 useful-links-links-hidden">
		<%= link_to contact_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Conact
			</div>
		<% end %>
		<%= link_to visiting_hours_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Visiting hours
			</div>
		<% end %>
		<%= link_to academic_year_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Academic year
			</div>
		<% end %>
		<a href="http://programy.p.lodz.pl/?s=glowna&l=en">
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> ECTS programmes
			</div>
		</a>
		<%= link_to application_forms_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Application forms
			</div>
		<% end %>
	</div>

</div>

app/views/shared/grades/_grades_sem1.html.erb
<table>
      <colgroup>
        <col class="1/5">
        <col class="1/5">
        <col class="2/5">
        <col class="1/5">
      </colgroup>
      <thead>
        <tr>
          <th class="compact-hidden">Subject ID</th>
          <th>Subject Name</th>
          <th>Tutor</th>
          <th>Grade</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td class="compact-hidden">00 1450</td>
          <td>Electronics</td>
          <td>PhD Mariusz Piotrowicz</td>
          <td>3.5</td>
        </tr>
        <tr>
          <td class="compact-hidden">21 0017</td>
          <td>Mathematics I</td>
          <td>PhD Jakub Szczepaniak</td>
          <td>5</td>
        </tr>
        <tr>
          <td class="compact-hidden">90 2300</td>
          <td>Technical English</td>
          <td>MS Joanna Milosz-Bartczak</td>
          <td>4</td>
        </tr>
        <tr>
          <td class="compact-hidden">06 4055</td>
          <td>Scripting Languages</td>
          <td>PhD Witold Maranda</td>
          <td>4.5</td>
        </tr>
      </tbody>
    </table>

app/views/shared/grades/_grades_sem2.html.erb
<table>
		  <colgroup>
		    <col class="1/5">
		    <col class="1/5">
		    <col class="2/5">
		    <col class="1/5">
		  </colgroup>
		  <thead>
		    <tr>
		      <th class="compact-hidden">Subject ID</th>
		      <th>Subject Name</th>
		      <th>Tutor</th>
		      <th>Grade</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td class="compact-hidden">00 1450</td>
		      <td>Electronics</td>
		      <td>PhD Mariusz Piotrowicz</td>
		      <td>5</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">21 0017</td>
		      <td>Mathematics I</td>
		      <td>PhD Jakub Szczepaniak</td>
		      <td>Failed</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">90 2300</td>
		      <td>Technical English</td>
		      <td>MS Joanna Milosz-Bartczak</td>
		      <td>4</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">06 4055</td>
		      <td>Scripting Languages</td>
		      <td>PhD Witold Maranda</td>
		      <td>4</td>
		    </tr>
		  </tbody>
		</table>

app/views/shared/grades/_grades_sem3.html.erb
<table>
		  <colgroup>
		    <col class="1/5">
		    <col class="1/5">
		    <col class="2/5">
		    <col class="1/5">
		  </colgroup>
		  <thead>
		    <tr>
		      <th class="compact-hidden">Subject ID</th>
		      <th>Subject Name</th>
		      <th>Tutor</th>
		      <th>Grade</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td class="compact-hidden">00 1450</td>
		      <td>Electronics</td>
		      <td>PhD Mariusz Piotrowicz</td>
		      <td>3</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">21 0017</td>
		      <td>Mathematics I</td>
		      <td>PhD Jakub Szczepaniak</td>
		      <td>4.5</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">90 2300</td>
		      <td>Technical English</td>
		      <td>MS Joanna Milosz-Bartczak</td>
		      <td>3</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">06 4055</td>
		      <td>Scripting Languages</td>
		      <td>PhD Witold Maranda</td>
		      <td>4</td>
		    </tr>
		  </tbody>
		</table>

app/views/shared/grades/_grades_sem4.html.erb
<table>
		  <colgroup>
		    <col class="1/5">
		    <col class="1/5">
		    <col class="2/5">
		    <col class="1/5">
		  </colgroup>
		  <thead>
		    <tr>
		      <th class="compact-hidden">Subject ID</th>
		      <th>Subject Name</th>
		      <th>Tutor</th>
		      <th>Grade</th>
		    </tr>
		  </thead>
		  <tbody>
		    <tr>
		      <td class="compact-hidden">00 1450</td>
		      <td>Electronics</td>
		      <td>PhD Mariusz Piotrowicz</td>
		      <td>5</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">21 0017</td>
		      <td>Mathematics I</td>
		      <td>PhD Jakub Szczepaniak</td>
		      <td>5</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">90 2300</td>
		      <td>Technical English</td>
		      <td>MS Joanna Milosz-Bartczak</td>
		      <td>5</td>
		    </tr>
		    <tr>
		      <td class="compact-hidden">06 4055</td>
		      <td>Scripting Languages</td>
		      <td>PhD Witold Maranda</td>
		      <td>5</td>
		    </tr>
		  </tbody>
		</table>

app/views/useful_links/index.html.erb
<div class="grid grid-center useful-links hidden medium-visible compact-visible">

	<div class="grid-item grid-center 1/1 mobile useful-links-links-visible">
		<%= link_to contact_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Conact
			</div>
		<% end %>
		<%= link_to visiting_hours_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Visiting hours
			</div>
		<% end %>
		<%= link_to academic_year_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Academic year
			</div>
		<% end %>
		<a href="http://programy.p.lodz.pl/?s=glowna&l=en">
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> ECTS programmes
			</div>
		</a>
		<%= link_to application_forms_index_path do %>
			<div class="grid-item 1/1 useful-links-link">
				<i class="fa fa-angle-right"></i> Application forms
			</div>
		<% end %>
	</div>

</div>

<div class="grid medium-hidden compact-hidden">

	<%= render 'shared/announcements' %>

</div>